trigger:
- main

variables:
  TF_DIR: envs/dev

stages:

# -----------------------
# STAGE 1: PLAN
# -----------------------
- stage: Plan
  displayName: Terraform Plan
  jobs:
  - job: PlanJob
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-azure-infra-service'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Navigating to Terraform directory..."
          cd $(TF_DIR)

          echo "Initializing Terraform..."
          terraform init

          echo "Validating Terraform..."
          terraform validate

          echo "Running Terraform Plan..."
          terraform plan -out=tfplan

    - publish: $(TF_DIR)/tfplan
      artifact: tfplan


# -----------------------
# STAGE 2: APPLY
# -----------------------
- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan
  condition: succeeded()

  jobs:
  - deployment: ApplyJob
    environment: dev   # enable approvals here in UI
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - download: current
            artifact: tfplan

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'my-azure-infra-service'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Navigating to Terraform directory..."
                cd $(TF_DIR)

                echo "Copying tfplan from artifact location..."
                cp $(Pipeline.Workspace)/tfplan/tfplan .

                echo "Initializing Terraform..."
                terraform init

                echo "Applying Terraform plan..."
                terraform apply -auto-approve tfplan
