trigger:
- main

variables:
  TF_DIR: envs/dev

stages:

# -----------------------
# STAGE 1: PLAN
# -----------------------
- stage: Plan
  displayName: Terraform Plan
  jobs:
  - job: PlanJob
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-azure-infra-service'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd $(TF_DIR)
          terraform init
          terraform validate
          terraform plan -out=tfplan

    - publish: $(TF_DIR)/tfplan
      artifact: tfplan

# -----------------------
# STAGE 2: APPLY
# -----------------------
- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan
  condition: succeeded()

  jobs:
  - deployment: ApplyJob
    environment: dev   # enables approval
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self
          - download: current
            artifact: tfplan

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'my-azure-infra-service'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                cd $(TF_DIR)
                terraform init
                terraform apply -auto-approve tfplan
